from tkinter import *
from tkinter import ttk

root = Tk()
treeview = ttk.Treeview(root)
treeview.pack()
treeview.insert('', '0', 'item1', text = 'First Item')
treeview.insert('', '1', 'item2', text = 'Second Item')
treeview.insert('','end', 'item3', text = 'Third Item')
logo = PhotoImage(file = 'Chapter 5\8bit shades.gif').subsample(20,20)
treeview.insert('item2', 'end', 'shades logo', text = 'shades', image = logo)
treeview.config(height = 5)
treeview.move('item2','item1', 'end')
treeview.item('item1', open = True)
print(treeview.item('item1', 'open'))
treeview.detach('item3')
treeview.move('item3', 'item2','0')
treeview.delete('item3')
treeview.config(columns = ('version'))
treeview.column('version', width = 50, anchor = 'center')
treeview.column('#0', width = 150)
treeview.heading('version', text = 'Version')
treeview.set('shades logo', 'version', '8bit')
treeview.item('shades logo', tags = ('accessory'))
treeview.tag_configure('accessory', background = 'yellow')
def callback(event):
    print(treeview.selection())
treeview.bind('<<TreeviewSelect>>', callback)
treeview.config(selectmode = 'browse')
treeview.config(selectmode = 'none')
treeview.selection_add('item1')
treeview.selection_remove('item1')
treeview.selection_toggle('item1')

root.mainloop()